# Generated by Django 4.1.7 on 2023-08-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('variable', 'Variable'), ('group', 'Group')], max_length=20)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hsn', models.CharField(max_length=20)),
                ('barcode_1', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode_2', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode_3', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode_4', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode_5', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_qty', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSDemo.business')),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='item_master',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='POSDemo.itemmaster'),
            preserve_default=False,
        ),
    ]
