# Generated by Django 4.1.7 on 2023-08-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0002_itemmaster_sales_item_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer', to='POSDemo.storemaster'),
            preserve_default=False,
        ),
    ]
