# Generated by Django 4.1.7 on 2023-08-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0003_customer_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAttributesOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSDemo.itemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hsn', models.CharField(max_length=20)),
                ('barcode_1', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode_2', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode_3', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode_4', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode_5', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_qty', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSDemo.itemattribute')),
                ('item_attribute_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSDemo.itemattributesoptions')),
                ('item_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSDemo.itemmaster')),
            ],
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='item_attribute_option_ids',
            field=models.ManyToManyField(related_name='item_attributes', to='POSDemo.itemattributesoptions'),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='item_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSDemo.itemmaster'),
        ),
        migrations.AddField(
            model_name='sales',
            name='item_variation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='POSDemo.itemvariation'),
            preserve_default=False,
        ),
    ]
