# Generated by Django 4.1.7 on 2023-08-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0004_itemattribute_itemattributesoptions_itemvariation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('stock_qty', models.PositiveIntegerField()),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expire_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSDemo.itemmaster')),
                ('item_variation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POSDemo.itemvariation')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSDemo.storemaster')),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='store_stock',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='POSDemo.storestock'),
            preserve_default=False,
        ),
    ]
