# Generated by Django 4.1.7 on 2023-03-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0010_alter_orders_total_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity_type', models.CharField(choices=[('GM', 'Gram'), ('LT', 'Litre'), ('UNIT', 'Units')], default='UNIT', max_length=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
