# Generated by Django 4.1.7 on 2023-03-20 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0011_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('main_category', models.ManyToManyField(related_name='sub_category', to='POSDemo.categories')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_sub_category', to='POSDemo.subcategory'),
        ),
    ]
