# Generated by Django 4.1.7 on 2023-03-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0012_subcategory_product_product_sub_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='ProductInventory',
        ),
    ]
