# Generated by Django 4.1.7 on 2023-03-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0014_company_remove_product_produc_quantity_in_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_Wise_Employee_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('designation_for_the_day', models.CharField(max_length=30)),
                ('time_of_joining', models.DateTimeField()),
                ('cash_collected', models.IntegerField()),
                ('time_of_leaving', models.DateTimeField()),
                ('employee_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Day_Wise_employee', to='POSDemo.employee')),
                ('orders_handled', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='POSDemo.orders')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventoryManagement',
            fields=[
                ('date_of_update', models.DateTimeField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('quantity_type', models.CharField(choices=[('GM', 'Gram'), ('LT', 'Litre'), ('UNIT', 'Units')], default='UNIT', max_length=10)),
                ('quantity_added', models.IntegerField(blank=True)),
                ('quantity_removed', models.IntegerField(blank=True)),
                ('remaining_quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity_in_inventory',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
    ]
