# Generated by Django 4.1.7 on 2023-03-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0018_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity_type',
            field=models.CharField(choices=[('GM', 'Gram'), ('LT', 'Litre'), ('PIECE', 'Pieces')], default='PIECE', max_length=10),
        ),
    ]
