# Generated by Django 4.1.7 on 2023-03-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0019_alter_product_product_quantity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wastage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_type', models.CharField(max_length=10)),
                ('wasted_amount', models.IntegerField()),
                ('date_entered', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='POSDemo.product')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Return_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('date_and_time_of_return', models.DateTimeField()),
                ('reson_for_return', models.CharField(max_length=200)),
                ('customer_returned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='POSDemo.customer')),
                ('employee_handled', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='POSDemo.employee')),
            ],
        ),
    ]
