# Generated by Django 4.1.7 on 2023-03-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0020_wastage_item_return_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('contact_number', models.SmallIntegerField()),
                ('whatsapp_number', models.CharField(blank=True, max_length=12)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=20)),
                ('pin', models.SmallIntegerField()),
                ('country', models.CharField(max_length=20)),
                ('pan_card_number', models.CharField(max_length=20)),
                ('date_of_entry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField()),
                ('business_name', models.CharField(max_length=50)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_phone', models.SmallIntegerField(blank=True)),
                ('business_address', models.CharField(max_length=300)),
                ('business_city', models.CharField(max_length=20)),
                ('business_pin', models.SmallIntegerField()),
                ('business_state', models.CharField(max_length=20)),
                ('business_country', models.CharField(max_length=10)),
                ('business_pan', models.CharField(max_length=15)),
                ('business_gst_number', models.CharField(max_length=100)),
                ('data_entered_on', models.DateField()),
                ('owned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='business', to='POSDemo.owner')),
            ],
        ),
    ]
