# Generated by Django 4.1.7 on 2023-03-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0021_owner_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
