# Generated by Django 4.1.7 on 2023-03-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0022_alter_owner_contact_number_alter_owner_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='contact_number',
            field=models.CharField(max_length=12),
        ),
    ]
