# Generated by Django 4.1.7 on 2023-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0023_alter_owner_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_id',
        ),
        migrations.AlterField(
            model_name='business',
            name='business_phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_pin',
            field=models.IntegerField(),
        ),
    ]
