# Generated by Django 4.1.7 on 2023-03-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0025_alter_business_business_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owner_id',
        ),
    ]
