# Generated by Django 4.1.7 on 2023-03-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0026_remove_owner_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_pan',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pan_card_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
