# Generated by Django 4.1.7 on 2023-03-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0028_alter_owner_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='storeInventoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity_type', models.CharField(max_length=5)),
                ('product_quantity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='storeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_location', models.CharField(max_length=200)),
                ('associated_business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='business', to='POSDemo.business')),
                ('store_inventory', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='POSDemo.storeinventorymaster')),
            ],
        ),
    ]
