# Generated by Django 4.1.7 on 2023-03-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0029_storeinventorymaster_storemaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemaster',
            name='store_inventory',
        ),
        migrations.AddField(
            model_name='storeinventorymaster',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='POSDemo.storemaster'),
        ),
    ]
