# Generated by Django 4.1.7 on 2023-03-28 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0031_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='token_expiry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BusinessInventoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField()),
                ('product_name', models.CharField(max_length=150)),
                ('product_quantity_type', models.CharField(max_length=5)),
                ('product_quantity', models.CharField(max_length=20)),
                ('associated_business', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='POSDemo.business')),
            ],
        ),
    ]
