# Generated by Django 4.1.7 on 2023-03-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0032_auth_token_expiry_businessinventorymaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_gst_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_pan',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
