# Generated by Django 4.1.7 on 2023-03-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0033_alter_business_business_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='user_ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pan_card_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pin',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='owner',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
