# Generated by Django 4.1.7 on 2023-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0034_auth_user_ip_alter_owner_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='token_expiry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
