# Generated by Django 4.1.7 on 2023-03-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0035_alter_auth_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='user_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
