# Generated by Django 4.1.7 on 2023-03-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0036_auth_user_password_alter_auth_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
