# Generated by Django 4.1.7 on 2023-03-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0038_businessinventorymaster_action_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeinventorymaster',
            old_name='store',
            new_name='associated_store',
        ),
        migrations.AddField(
            model_name='businessinventorymaster',
            name='price_per_unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='storeinventorymaster',
            name='action',
            field=models.CharField(choices=[('ADDED', 'product added'), ('REMOVED', 'product removed')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='storeinventorymaster',
            name='price_per_unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='storeinventorymaster',
            name='product_quantity_type',
            field=models.CharField(choices=[('GM', 'gram'), ('PIECE', 'pieces'), ('LTR', 'litre')], max_length=5),
        ),
    ]
