# Generated by Django 4.1.7 on 2023-03-30 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0039_rename_store_storeinventorymaster_associated_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinventorymaster',
            name='associated_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='POSDemo.business'),
        ),
    ]
