# Generated by Django 4.1.7 on 2023-03-30 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0042_storeinventorymaster_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemaster',
            name='associated_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='POSDemo.owner'),
        ),
    ]
