# Generated by Django 4.1.7 on 2023-03-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0043_storemaster_associated_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemaster',
            name='associated_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='POSDemo.owner'),
        ),
    ]
