# Generated by Django 4.1.7 on 2023-03-31 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0045_alter_storemaster_associated_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='owned_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='business', to='POSDemo.owner'),
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('adhaar', models.CharField(max_length=12)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='POSDemo.storemaster')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('have_access', models.BooleanField()),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authentication', to='POSDemo.employeemaster')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_auth', to='POSDemo.storemaster')),
            ],
        ),
    ]
