# Generated by Django 4.1.7 on 2023-03-31 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0046_alter_business_owned_by_employeemaster_employeeauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=20)),
                ('pan_card_number', models.CharField(max_length=10, unique=True)),
                ('date_of_entry', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='company',
        ),
        migrations.RemoveField(
            model_name='day_wise_employee_management',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='day_wise_employee_management',
            name='orders_handled',
        ),
        migrations.RemoveField(
            model_name='item_return_management',
            name='customer_returned',
        ),
        migrations.RemoveField(
            model_name='item_return_management',
            name='employee_handled',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer_ordered',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sub_category',
        ),
        migrations.DeleteModel(
            name='ProductInventoryManagement',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='wastage',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='country',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='pan_card_number',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='pin',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Day_Wise_Employee_Management',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Item_Return_Management',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='Wastage',
        ),
        migrations.AddField(
            model_name='ownerdetails',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='POSDemo.owner'),
        ),
    ]
