# Generated by Django 4.1.7 on 2023-04-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0050_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModeOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_ID', models.CharField(blank=True, max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='POSDemo.business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='POSDemo.employeemaster')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='POSDemo.modeofpayment')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='POSDemo.storemaster')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_ID', models.CharField(blank=True, max_length=50)),
                ('item_total', models.CharField(max_length=100)),
                ('product_barcode', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_mrp', models.CharField(max_length=50)),
                ('item_rate', models.CharField(max_length=50)),
                ('item_qty', models.CharField(max_length=10)),
                ('item_row_total', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesregister', to='POSDemo.business')),
                ('item_gst', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesregister', to='POSDemo.taxmaster')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesregister', to='POSDemo.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesregister', to='POSDemo.storemaster')),
            ],
        ),
    ]
