# Generated by Django 4.1.7 on 2023-04-02 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0053_genbill_salespending_bill_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespending',
            name='bill_id',
        ),
        migrations.AlterField(
            model_name='salesregister',
            name='bill_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesregister', to='POSDemo.genbill'),
        ),
        migrations.RemoveField(
            model_name='salesregister',
            name='item',
        ),
        migrations.AddField(
            model_name='salesregister',
            name='item',
            field=models.ManyToManyField(related_name='salesregister', to='POSDemo.product'),
        ),
    ]
