# Generated by Django 4.1.7 on 2023-04-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0054_remove_salespending_bill_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespending',
            name='mrp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
