# Generated by Django 4.1.7 on 2023-04-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0055_salespending_mrp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesregister',
            old_name='item_gst',
            new_name='gst',
        ),
        migrations.RenameField(
            model_name='salesregister',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='salesregister',
            old_name='item_name',
            new_name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='salesregister',
            name='item_mrp',
        ),
        migrations.RemoveField(
            model_name='salesregister',
            name='item_qty',
        ),
        migrations.RemoveField(
            model_name='salesregister',
            name='item_rate',
        ),
        migrations.RemoveField(
            model_name='salesregister',
            name='item_row_total',
        ),
        migrations.RemoveField(
            model_name='salesregister',
            name='item_total',
        ),
        migrations.AddField(
            model_name='salesregister',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesregister', to='POSDemo.employeemaster'),
        ),
        migrations.AddField(
            model_name='salesregister',
            name='mrp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesregister',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesregister',
            name='purchase_rate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesregister',
            name='row_total',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesregister',
            name='sale_rate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesregister',
            name='item_barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
