# Generated by Django 4.1.7 on 2023-04-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0056_rename_item_gst_salesregister_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesregister',
            name='product',
        ),
        migrations.AddField(
            model_name='salesregister',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesregister', to='POSDemo.product'),
        ),
    ]
