# Generated by Django 4.1.7 on 2023-04-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0057_remove_salesregister_product_salesregister_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesregister',
            name='bill_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
