# Generated by Django 4.1.7 on 2023-04-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0058_salesregister_bill_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinventorymaster',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='storeinventorymaster',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='storeinventorymaster',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='storeinventorymaster',
            name='product_quantity_type',
        ),
        migrations.AddField(
            model_name='storeinventorymaster',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='storeinventory', to='POSDemo.business'),
        ),
        migrations.AddField(
            model_name='storeinventorymaster',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='storeinventory', to='POSDemo.product'),
        ),
        migrations.AlterField(
            model_name='storeinventorymaster',
            name='associated_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='storeinventory', to='POSDemo.storemaster'),
        ),
    ]
