# Generated by Django 4.1.7 on 2023-04-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0059_remove_storeinventorymaster_price_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinventorymaster',
            name='store_owner',
        ),
        migrations.AddField(
            model_name='storeinventorymaster',
            name='available',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
