# Generated by Django 4.1.7 on 2023-04-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0060_remove_storeinventorymaster_store_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
