# Generated by Django 4.1.7 on 2023-04-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0062_alter_auth_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='token_expiry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
