# Generated by Django 4.1.7 on 2023-04-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0064_alter_auth_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinventorymaster',
            name='action',
        ),
    ]
