# Generated by Django 4.1.7 on 2023-04-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0065_remove_storeinventorymaster_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hsn',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
