# Generated by Django 4.1.7 on 2023-04-03 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0066_alter_product_hsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemaster',
            name='associated_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='store', to='POSDemo.business'),
        ),
    ]
