# Generated by Django 4.1.7 on 2023-04-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0067_alter_storemaster_associated_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='data_entered_on',
            new_name='date_of_entry',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_gst_number',
            new_name='gst_number',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='owned_by',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_pan',
            new_name='pan',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_pin',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_state',
            new_name='state',
        ),
    ]
