# Generated by Django 4.1.7 on 2023-04-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0068_rename_business_address_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='POSDemo.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('GM', 'gram'), ('PIECE', 'pieces'), ('LTR', 'litre'), ('MTR', 'meter')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='POSDemo.storemaster'),
        ),
    ]
