# Generated by Django 4.1.7 on 2023-04-03 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0069_product_business_product_quantity_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessinventorymaster',
            old_name='product_quantity',
            new_name='available',
        ),
        migrations.RemoveField(
            model_name='businessinventorymaster',
            name='action',
        ),
        migrations.RemoveField(
            model_name='businessinventorymaster',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='businessinventorymaster',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='businessinventorymaster',
            name='product_quantity_type',
        ),
        migrations.AddField(
            model_name='businessinventorymaster',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='businessinventory', to='POSDemo.product'),
        ),
    ]
