# Generated by Django 4.1.7 on 2023-04-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0070_rename_product_quantity_businessinventorymaster_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
    ]
