# Generated by Django 4.1.7 on 2023-04-04 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0071_remove_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesregister',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesregister', to='POSDemo.customer'),
        ),
    ]
