# Generated by Django 4.1.7 on 2023-04-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0073_alter_employeemaster_adhaar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JwtAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt', models.CharField(max_length=300)),
                ('expiry', models.DateTimeField()),
            ],
        ),
    ]
