# Generated by Django 4.1.7 on 2023-04-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0074_jwtauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionDetails',
        ),
    ]
