# Generated by Django 4.1.7 on 2023-04-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0075_delete_transactiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetailsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=100)),
                ('date_of_entry', models.DateTimeField()),
                ('mop', models.JSONField(default=list)),
                ('products', models.JSONField(default=list)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactiondetails', to='POSDemo.business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactiondetails', to='POSDemo.employeemaster')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactiondetails', to='POSDemo.storemaster')),
            ],
        ),
    ]
