# Generated by Django 4.1.7 on 2023-04-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0077_alter_transactiondetailsmaster_mop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturnRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=100, null=True)),
                ('item_barcode', models.CharField(blank=True, max_length=100)),
                ('product_quantity', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('mrp', models.CharField(max_length=50, null=True)),
                ('purchase_rate', models.CharField(max_length=50, null=True)),
                ('sale_rate', models.CharField(max_length=20, null=True)),
                ('row_total', models.CharField(max_length=100, null=True)),
                ('bill_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesreturn', to='POSDemo.genbill')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesreturn', to='POSDemo.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesreturn', to='POSDemo.customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesreturn', to='POSDemo.employeemaster')),
                ('gst', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesreturn', to='POSDemo.taxmaster')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesreturn', to='POSDemo.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesreturn', to='POSDemo.storemaster')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnTransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=100)),
                ('date_of_entry', models.DateTimeField()),
                ('mop', models.JSONField()),
                ('products', models.JSONField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='returntransaction', to='POSDemo.business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='returntransaction', to='POSDemo.employeemaster')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='returntransaction', to='POSDemo.storemaster')),
            ],
        ),
    ]
