# Generated by Django 4.1.7 on 2023-04-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0078_salesreturnregister_returntransactiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateTimeField()),
                ('dealer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('quantity', models.CharField(max_length=20)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prchaseregister', to='POSDemo.dealermaster')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchaseregister', to='POSDemo.product')),
            ],
        ),
        migrations.RenameField(
            model_name='employeeauth',
            old_name='token',
            new_name='jwt',
        ),
        migrations.RenameField(
            model_name='salesreturnregister',
            old_name='product_quantity',
            new_name='quantity_returned',
        ),
        migrations.RemoveField(
            model_name='salesreturnregister',
            name='bill_ID',
        ),
        migrations.RemoveField(
            model_name='salesreturnregister',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='salesreturnregister',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='salesreturnregister',
            name='purchase_rate',
        ),
        migrations.RemoveField(
            model_name='salesreturnregister',
            name='row_total',
        ),
        migrations.RemoveField(
            model_name='salesreturnregister',
            name='sale_rate',
        ),
        migrations.AddField(
            model_name='salespending',
            name='bill_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salespending', to='POSDemo.genbill'),
        ),
        migrations.CreateModel(
            name='PurchaseTransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateTimeField()),
                ('mop', models.JSONField()),
                ('related_purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purtransactiondetails', to='POSDemo.purchaseregister')),
            ],
        ),
    ]
