# Generated by Django 4.1.7 on 2023-04-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0079_dealermaster_purchaseregister_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_of_entry', models.TimeField()),
                ('time_of_relief', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance', to='POSDemo.employeemaster')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employeeAttendance', to='POSDemo.storemaster')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnSalesPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateTimeField()),
                ('return_quantity', models.CharField(max_length=50, null=True)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='returnsalespending', to='POSDemo.genbill')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='returnsalespending', to='POSDemo.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='returnsalespending', to='POSDemo.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='returnsalespending', to='POSDemo.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='returnsalespending', to='POSDemo.storemaster')),
            ],
        ),
        migrations.AddField(
            model_name='salespending',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salespending', to='POSDemo.customer'),
        ),
        migrations.DeleteModel(
            name='SalesReturnRegister',
        ),
    ]
