# Generated by Django 4.1.7 on 2023-04-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0082_rename_bill_id_returnsalespending_bill_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnsalespending',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='returnsalespending', to='POSDemo.customer'),
        ),
    ]
