# Generated by Django 4.1.7 on 2023-04-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0084_alter_returnsalespending_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetailsmaster',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactiondetails', to='POSDemo.genbill'),
        ),
    ]
