# Generated by Django 4.1.7 on 2023-04-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0085_alter_transactiondetailsmaster_bill_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100, unique=True)),
                ('modified_on', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credential', to='POSDemo.employeemaster')),
            ],
        ),
    ]
