# Generated by Django 4.1.7 on 2023-04-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0086_employeecredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='password',
        ),
        migrations.AddField(
            model_name='employeecredential',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
