# Generated by Django 4.1.7 on 2023-04-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0087_remove_employeemaster_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeauth',
            old_name='employee_name',
            new_name='employee',
        ),
    ]
