# Generated by Django 4.1.7 on 2023-04-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0088_rename_employee_name_employeeauth_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variable',
            field=models.BooleanField(null=True),
        ),
    ]
