# Generated by Django 4.1.7 on 2023-04-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0089_product_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('MRP', models.CharField(max_length=20)),
                ('purchase_rate', models.CharField(max_length=20)),
                ('sale_rate', models.CharField(max_length=20)),
                ('hsn', models.CharField(blank=True, max_length=7, null=True)),
                ('quantity_type', models.CharField(choices=[('GM', 'gram'), ('PIECE', 'pieces'), ('LTR', 'litre'), ('MTR', 'meter')], max_length=5)),
                ('gst', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variableproduct', to='POSDemo.taxmaster')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variableproduct', to='POSDemo.product')),
            ],
        ),
    ]
