# Generated by Django 4.1.7 on 2023-04-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0092_rename_dealer_purchaseregister_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseregister',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
