# Generated by Django 4.1.7 on 2023-04-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0093_purchaseregister_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseregister',
            name='updated_at',
        ),
    ]
