# Generated by Django 4.1.7 on 2023-04-12 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0094_remove_purchaseregister_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermaster',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier', to='POSDemo.storemaster'),
        ),
    ]
