# Generated by Django 4.1.7 on 2023-04-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0098_remove_employeeauth_store_employeeauth_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=100)),
                ('product_quantity', models.CharField(max_length=20)),
                ('quantity_type', models.CharField(choices=[('GM', 'gram'), ('PIECE', 'pieces'), ('LTR', 'litre'), ('MTR', 'meter')], max_length=5)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchasepending', to='POSDemo.suppliermaster')),
            ],
        ),
    ]
