# Generated by Django 4.1.7 on 2023-04-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0101_purchaseregister_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseregister',
            name='purchase_rate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
