# Generated by Django 4.1.7 on 2023-04-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0103_rename_product_purchasepending_purchase_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('bill_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseregister',
            name='bill_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
