# Generated by Django 4.1.7 on 2023-04-17 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0104_purchasebill_purchaseregister_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetransactiondetails',
            name='bill_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasetransactiondetails',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchasetransaction', to='POSDemo.suppliermaster'),
        ),
    ]
