# Generated by Django 4.1.7 on 2023-04-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0105_purchasetransactiondetails_bill_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasetransactiondetails',
            name='related_purchase',
        ),
    ]
