# Generated by Django 4.1.7 on 2023-04-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0108_permissions_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Permission',
        ),
        migrations.AddField(
            model_name='roles',
            name='permisssions',
            field=models.ManyToManyField(null=True, related_name='roles', to='POSDemo.permission'),
        ),
    ]
