# Generated by Django 4.1.7 on 2023-04-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0109_rename_permissions_permission_roles_permisssions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='permisssions',
            field=models.ManyToManyField(related_name='roles', to='POSDemo.permission'),
        ),
    ]
