# Generated by Django 4.1.7 on 2023-04-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0114_rename_permisssions_roles_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='pin',
            field=models.CharField(max_length=6),
        ),
    ]
