# Generated by Django 4.1.7 on 2023-04-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0115_alter_business_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returntransactiondetails',
            name='products',
        ),
        migrations.AddField(
            model_name='returntransactiondetails',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='returntransactiondetails',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='returntransactiondetails', to='POSDemo.product'),
        ),
        migrations.AlterField(
            model_name='returntransactiondetails',
            name='mop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='returntransactiondetails', to='POSDemo.modeofpayment'),
        ),
    ]
