# Generated by Django 4.1.7 on 2023-04-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0117_remove_returntransactiondetails_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeofpayment',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mop', to='POSDemo.business'),
        ),
    ]
