# Generated by Django 4.1.7 on 2023-07-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0118_modeofpayment_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='role',
        ),
    ]
