# Generated by Django 4.1.7 on 2023-07-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0120_employeemaster_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='role',
        ),
    ]
