# Generated by Django 4.2.3 on 2023-07-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0121_remove_employeemaster_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='business',
        ),
        migrations.AlterField(
            model_name='business',
            name='owner_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='business', to='POSDemo.owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
