# Generated by Django 4.2.3 on 2023-07-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0122_remove_employeemaster_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='business',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='POSDemo.business'),
            preserve_default=False,
        ),
    ]
