# Generated by Django 4.2.3 on 2023-07-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0123_employeemaster_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='business',
        ),
    ]
