# Generated by Django 4.1.7 on 2023-07-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0124_remove_employeemaster_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='business',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='POSDemo.business'),
            preserve_default=False,
        ),
    ]
