# Generated by Django 4.1.7 on 2023-07-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0125_employeemaster_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='business',
        ),
    ]
