# Generated by Django 4.1.7 on 2023-07-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0126_remove_employeemaster_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storemaster',
            name='associated_owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store', to='POSDemo.owner'),
            preserve_default=False,
        ),
    ]
