# Generated by Django 4.1.7 on 2023-07-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0128_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Sales',
        ),
    ]
