from django.contrib import admin
from .models import *
from .models2 import Owner , Business, Sales, storeMaster , storeInventoryMaster , auth ,BusinessInventoryMaster , EmployeeMaster , EmployeeAuth  , Customer ,Product , TaxMaster ,  OwnerDetails, ModeOfPayment , Barcode  , SalesPending , GenBill , JwtAuth , TransactionDetailsMaster , ReturnSalesPending , ReturnTransactionDetails , SalesReturnRegister , EmployeeCredential ,  VariableProduct , PurchaseRegister , PurchaseTransactionDetails , SupplierMaster , Daily_employee_management , PurchasePending , Roles , Permission , Categories
'''
admin.site.register(ProductInventoryManagement)
admin.site.register(Day_Wise_Employee_Management)
admin.site.register(Product)
admin.site.register(Customer)
admin.site.register(Orders)
admin.site.register(Categories)
admin.site.register(SubCategory)
admin.site.register(Employee)
admin.site.register(Item_Return_Management)
admin.site.register(Wastage)
'''

admin.site.register(Sales)
admin.site.register(Owner)
admin.site.register(OwnerDetails)
admin.site.register(Business)
admin.site.register(BusinessInventoryMaster)
admin.site.register(storeMaster)
admin.site.register(storeInventoryMaster)
admin.site.register(auth)
admin.site.register(JwtAuth)
admin.site.register(EmployeeMaster)
admin.site.register(EmployeeAuth)
admin.site.register(EmployeeCredential)
admin.site.register(Customer)
admin.site.register(Product)
admin.site.register(VariableProduct)
admin.site.register(TaxMaster)
admin.site.register(ModeOfPayment)
admin.site.register(Barcode)
admin.site.register(TransactionDetailsMaster)
admin.site.register(SalesPending)
admin.site.register(GenBill)
admin.site.register(ReturnTransactionDetails)
admin.site.register(ReturnSalesPending)
admin.site.register(SalesReturnRegister)
admin.site.register(PurchaseRegister)
admin.site.register(PurchaseTransactionDetails),
admin.site.register(SupplierMaster)
admin.site.register(Daily_employee_management)
admin.site.register(PurchasePending)
admin.site.register(Roles)
admin.site.register(Permission)
admin.site.register(Categories)